name: CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Build ngtx
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: install dependencies
        run: npm install
      - name: build and test project
        run: npm test